# Generated by Django 3.2.19 on 2023-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
